language: node_js

node_js:
  - "12.13.0"
os:
  - linux

services: mongodb

git:
  quiet: true
  depth: 5

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - test
  - lint

jobs:
  include:
    - stage: test
      script:
        - yarn test
    - stage: lint
      script:
        - yarn lint

after_success:
  - echo $TRAVIS_TEST_RESULT
