version: "3"
services:
  images:
    container_name: images
    build: .
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongo:27017/images
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/app/src
      - ./views:/home/app/views
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.0.10-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
